# Переменные окружения (см. config.py). Пример:
# export API_ID=...
# export API_HASH=...
# export PHONE=+7...
# export OPENAI_API_KEY=sk-...
# export OPENAI_MODEL=gpt-4o-mini
# export HR_ACCOUNT=@hr_username
# export CANDIDATE_USERNAME=@candidate_username
# Плейсхолдеры приветствий: {name}=@username кандидата, остальные — resource/json/company_data.json
